
#server.port=8082
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#spring.datasource.url=jdbc:mysql://localhost:3306/myauction?characterEncoding=utf-8
#spring.datasource.username=root
#spring.datasource.password=12345
#spring.datasource.type=com.alibaba.druid.pool.DruidDataSource
#mybatis.type-aliases-package=com.shop.pojo
#mybatis.mapper-locations=classpath:mappings/*.xml
#
#
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql:///spring_boot?useUnicode=true&characterEncoding=UTF-8
    #    url: jdbc:mysql://localhost:3306/ssm?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root

#    文件上传选项配置
#  servlet:
#    multipart:
#      max-file-size:
server:
  port: 8086
#mybatis spring boot 自动配置 属性
mybatis:
#  因为 .xml mapper 的 type 加了包名，所以可以去掉
#  type-aliases-package: com.shop.pojo
  mapper-locations: [classpath:mappings/*.xml]

#  <!--  直接到 static 目录里-->
#  <link href="css/common.css" rel="stylesheet" type="text/css" />
#  <!--  不要这样-->


#  ##设置pageHelper的数据库方言
#pagehelper.helper-dialect=mysql
#reasonable 公平的 合理的
#pagehelper.reasonable=true
pagehelper:
  helper-dialect: mysql
  reasonable: true
#  <!--  <link href="./../static/css/common.css" rel="stylesheet" type="text/css" />-->
